"""
Parser for Code Taxonomy Analyst XML responses.

This module provides functions to parse XML taxonomies generated by the 
Code Taxonomy Analyst LLM into structured Python objects.
"""

import xml.etree.ElementTree as ET
from dataclasses import dataclass, field
from typing import List, Dict, Optional


@dataclass
class Metadata:
    """File metadata from taxonomy."""
    path: str
    purpose: str
    type: str
    file_order_priority: str  # 'config' or 'application'


@dataclass
class Concept:
    """Individual concept extracted from code."""
    id: str
    name: str
    category: str
    code: str
    what: str
    why: str
    how: str
    context: str
    alternatives: str
    tags: List[str]
    complexity: str  # 'beginner', 'intermediate', or 'advanced'


@dataclass
class CategoryCount:
    """Count of concepts by category."""
    name: str
    count: int


@dataclass
class ConceptRef:
    """Reference to a concept in the summary."""
    id: str
    name: str


@dataclass
class Summary:
    """Summary statistics for the taxonomy."""
    category_counts: List[CategoryCount]
    all_concepts: List[ConceptRef]
    tag_cloud: List[str]
    complexity_indicators: Dict[str, int]  # beginner, intermediate, advanced


@dataclass
class FileTaxonomy:
    """Complete taxonomy for a single file."""
    metadata: Metadata
    concepts: List[Concept]
    summary: Summary


def parse_taxonomy_xml(xml_text: str) -> FileTaxonomy:
    """
    Parse XML taxonomy response into structured Python objects.
    
    Args:
        xml_text: The raw XML string returned by the LLM
        
    Returns:
        FileTaxonomy object containing all parsed data
        
    Raises:
        ET.ParseError: If XML is malformed
        ValueError: If required elements are missing
    """
    # Parse XML
    root = ET.fromstring(xml_text)
    
    # Find the file element
    file_elem = root.find('file')
    if file_elem is None:
        raise ValueError("No <file> element found in taxonomy XML")
    
    # Parse metadata
    metadata_elem = file_elem.find('metadata')
    if metadata_elem is None:
        raise ValueError("No <metadata> element found in file")
    
    metadata = Metadata(
        path=_get_text(metadata_elem, 'path'),
        purpose=_get_text(metadata_elem, 'purpose'),
        type=_get_text(metadata_elem, 'type'),
        file_order_priority=_get_text(metadata_elem, 'file_order_priority')
    )
    
    # Parse concepts
    concepts_elem = file_elem.find('concepts')
    if concepts_elem is None:
        raise ValueError("No <concepts> element found in file")
    
    concepts = []
    for concept_elem in concepts_elem.findall('concept'):
        concept_id = concept_elem.get('id')
        if not concept_id:
            raise ValueError("Concept missing 'id' attribute")
        
        # Parse tags
        tags_elem = concept_elem.find('tags')
        tags = [tag.text for tag in tags_elem.findall('tag')] if tags_elem is not None else []
        
        concept = Concept(
            id=concept_id,
            name=_get_text(concept_elem, 'n'),
            category=_get_text(concept_elem, 'category'),
            code=_get_text(concept_elem, 'code'),
            what=_get_text(concept_elem, 'what'),
            why=_get_text(concept_elem, 'why'),
            how=_get_text(concept_elem, 'how'),
            context=_get_text(concept_elem, 'context'),
            alternatives=_get_text(concept_elem, 'alternatives'),
            tags=tags,
            complexity=_get_text(concept_elem, 'complexity')
        )
        concepts.append(concept)
    
    # Parse summary
    summary_elem = file_elem.find('summary')
    if summary_elem is None:
        raise ValueError("No <summary> element found in file")
    
    # Category counts
    category_counts = []
    category_counts_elem = summary_elem.find('category_counts')
    if category_counts_elem is not None:
        for cat_elem in category_counts_elem.findall('category'):
            category_counts.append(CategoryCount(
                name=cat_elem.get('name', ''),
                count=int(cat_elem.get('count', 0))
            ))
    
    # All concepts references
    all_concepts = []
    all_concepts_elem = summary_elem.find('all_concepts')
    if all_concepts_elem is not None:
        for ref_elem in all_concepts_elem.findall('concept_ref'):
            all_concepts.append(ConceptRef(
                id=ref_elem.get('id', ''),
                name=ref_elem.text or ''
            ))
    
    # Tag cloud
    tag_cloud = []
    tag_cloud_elem = summary_elem.find('tag_cloud')
    if tag_cloud_elem is not None:
        tag_cloud = [tag.text for tag in tag_cloud_elem.findall('tag') if tag.text]
    
    # Complexity indicators
    complexity_indicators = {}
    complexity_elem = summary_elem.find('complexity_indicators')
    if complexity_elem is not None:
        for level in ['beginner', 'intermediate', 'advanced']:
            level_elem = complexity_elem.find(level)
            if level_elem is not None and level_elem.text:
                complexity_indicators[level] = int(level_elem.text)
    
    summary = Summary(
        category_counts=category_counts,
        all_concepts=all_concepts,
        tag_cloud=tag_cloud,
        complexity_indicators=complexity_indicators
    )
    
    return FileTaxonomy(
        metadata=metadata,
        concepts=concepts,
        summary=summary
    )


def _get_text(element: ET.Element, tag_name: str, default: str = '') -> str:
    """
    Safely extract text from a child element.
    
    Args:
        element: Parent XML element
        tag_name: Name of child element to extract text from
        default: Default value if element not found or has no text
        
    Returns:
        Text content of the element, or default if not found
    """
    child = element.find(tag_name)
    if child is not None and child.text is not None:
        return child.text.strip()
    return default


def parse_multiple_taxonomies(xml_texts: List[str]) -> List[FileTaxonomy]:
    """
    Parse multiple taxonomy XML responses.
    
    Args:
        xml_texts: List of XML strings from multiple LLM responses
        
    Returns:
        List of FileTaxonomy objects
        
    Raises:
        ET.ParseError: If any XML is malformed
        ValueError: If any XML is missing required elements
    """
    return [parse_taxonomy_xml(xml) for xml in xml_texts]


def aggregate_concepts(taxonomies: List[FileTaxonomy]) -> Dict[str, List[Concept]]:
    """
    Aggregate concepts from multiple taxonomies by category.
    
    Args:
        taxonomies: List of FileTaxonomy objects
        
    Returns:
        Dictionary mapping category names to lists of concepts
    """
    aggregated = {}
    
    for taxonomy in taxonomies:
        for concept in taxonomy.concepts:
            category = concept.category
            if category not in aggregated:
                aggregated[category] = []
            aggregated[category].append(concept)
    
    return aggregated


def aggregate_tags(taxonomies: List[FileTaxonomy]) -> Dict[str, int]:
    """
    Aggregate all tags from multiple taxonomies with counts.
    
    Args:
        taxonomies: List of FileTaxonomy objects
        
    Returns:
        Dictionary mapping tag names to occurrence counts
    """
    tag_counts = {}
    
    for taxonomy in taxonomies:
        for concept in taxonomy.concepts:
            for tag in concept.tags:
                tag_counts[tag] = tag_counts.get(tag, 0) + 1
    
    return dict(sorted(tag_counts.items()))


def get_concepts_by_tag(taxonomies: List[FileTaxonomy], tag: str) -> List[Concept]:
    """
    Find all concepts that have a specific tag.
    
    Args:
        taxonomies: List of FileTaxonomy objects
        tag: Tag to search for
        
    Returns:
        List of Concept objects that include the specified tag
    """
    matching_concepts = []
    
    for taxonomy in taxonomies:
        for concept in taxonomy.concepts:
            if tag in concept.tags:
                matching_concepts.append(concept)
    
    return matching_concepts


def get_concepts_by_complexity(
    taxonomies: List[FileTaxonomy], 
    complexity: str
) -> List[Concept]:
    """
    Find all concepts of a specific complexity level.
    
    Args:
        taxonomies: List of FileTaxonomy objects
        complexity: Complexity level ('beginner', 'intermediate', 'advanced')
        
    Returns:
        List of Concept objects with the specified complexity
    """
    matching_concepts = []
    
    for taxonomy in taxonomies:
        for concept in taxonomy.concepts:
            if concept.complexity == complexity:
                matching_concepts.append(concept)
    
    return matching_concepts


def get_config_files(taxonomies: List[FileTaxonomy]) -> List[FileTaxonomy]:
    """
    Filter taxonomies to only configuration files.
    
    Args:
        taxonomies: List of FileTaxonomy objects
        
    Returns:
        List of FileTaxonomy objects with file_order_priority='config'
    """
    return [t for t in taxonomies if t.metadata.file_order_priority == 'config']


def get_application_files(taxonomies: List[FileTaxonomy]) -> List[FileTaxonomy]:
    """
    Filter taxonomies to only application files.
    
    Args:
        taxonomies: List of FileTaxonomy objects
        
    Returns:
        List of FileTaxonomy objects with file_order_priority='application'
    """
    return [t for t in taxonomies if t.metadata.file_order_priority == 'application']


def generate_summary_report(taxonomies: List[FileTaxonomy]) -> str:
    """
    Generate a human-readable summary report of all taxonomies.
    
    Args:
        taxonomies: List of FileTaxonomy objects
        
    Returns:
        Formatted string report
    """
    total_concepts = sum(len(t.concepts) for t in taxonomies)
    config_files = get_config_files(taxonomies)
    app_files = get_application_files(taxonomies)
    
    # Aggregate by category
    category_totals = {}
    for taxonomy in taxonomies:
        for cat_count in taxonomy.summary.category_counts:
            category_totals[cat_count.name] = category_totals.get(cat_count.name, 0) + cat_count.count
    
    # Aggregate by complexity
    complexity_totals = {'beginner': 0, 'intermediate': 0, 'advanced': 0}
    for taxonomy in taxonomies:
        for level, count in taxonomy.summary.complexity_indicators.items():
            complexity_totals[level] = complexity_totals.get(level, 0) + count
    
    # Get all unique tags
    all_tags = aggregate_tags(taxonomies)
    
    # Build report
    lines = [
        "=" * 80,
        "CODE TAXONOMY SUMMARY REPORT",
        "=" * 80,
        "",
        f"Total Files Analyzed: {len(taxonomies)}",
        f"  - Configuration Files: {len(config_files)}",
        f"  - Application Files: {len(app_files)}",
        f"Total Concepts Extracted: {total_concepts}",
        "",
        "CONCEPTS BY CATEGORY:",
        "-" * 80,
    ]
    
    for category, count in sorted(category_totals.items(), key=lambda x: x[1], reverse=True):
        lines.append(f"  {category}: {count}")
    
    lines.extend([
        "",
        "CONCEPTS BY COMPLEXITY:",
        "-" * 80,
        f"  Beginner: {complexity_totals['beginner']}",
        f"  Intermediate: {complexity_totals['intermediate']}",
        f"  Advanced: {complexity_totals['advanced']}",
        "",
        f"UNIQUE TAGS: {len(all_tags)}",
        "-" * 80,
    ])
    
    # Show top 20 most common tags
    top_tags = sorted(all_tags.items(), key=lambda x: x[1], reverse=True)[:20]
    for tag, count in top_tags:
        lines.append(f"  {tag}: {count}")
    
    if len(all_tags) > 20:
        lines.append(f"  ... and {len(all_tags) - 20} more tags")
    
    lines.extend([
        "",
        "FILES ANALYZED:",
        "-" * 80,
    ])
    
    # List config files first, then application files
    for taxonomy in config_files + app_files:
        file_type = "CONFIG" if taxonomy.metadata.file_order_priority == 'config' else "APP"
        lines.append(f"  [{file_type}] {taxonomy.metadata.path} ({len(taxonomy.concepts)} concepts)")
    
    lines.extend([
        "",
        "=" * 80,
    ])
    
    return "\n".join(lines)


# Example usage
if __name__ == "__main__":
    # Example XML (truncated for demonstration)
    example_xml = """<?xml version="1.0" encoding="UTF-8"?>
<taxonomy>
  <file>
    <metadata>
      <path><![CDATA[/src/components/Button.tsx]]></path>
      <purpose><![CDATA[Reusable button component]]></purpose>
      <type><![CDATA[component]]></type>
      <file_order_priority><![CDATA[application]]></file_order_priority>
    </metadata>
    
    <concepts>
      <concept id="CONCEPT-001">
        <n><![CDATA[Named Import with Default]]></n>
        <category><![CDATA[Import/Module Management]]></category>
        <code><![CDATA[import React, { useState } from "react";]]></code>
        <what><![CDATA[Combines default and named imports]]></what>
        <why><![CDATA[Efficient import syntax]]></why>
        <how><![CDATA[ES6 module syntax]]></how>
        <context><![CDATA[Importing React and useState hook]]></context>
        <alternatives><![CDATA[Separate import statements]]></alternatives>
        <tags>
          <tag>import</tag>
          <tag>es6-modules</tag>
          <tag>react</tag>
        </tags>
        <complexity>beginner</complexity>
      </concept>
    </concepts>
    
    <summary>
      <category_counts>
        <category name="Import/Module Management" count="1"/>
      </category_counts>
      
      <all_concepts>
        <concept_ref id="CONCEPT-001"><![CDATA[Named Import with Default]]></concept_ref>
      </all_concepts>
      
      <tag_cloud>
        <tag>es6-modules</tag>
        <tag>import</tag>
        <tag>react</tag>
      </tag_cloud>
      
      <complexity_indicators>
        <beginner>1</beginner>
        <intermediate>0</intermediate>
        <advanced>0</advanced>
      </complexity_indicators>
    </summary>
  </file>
</taxonomy>"""
    
    # Parse the XML
    taxonomy = parse_taxonomy_xml(example_xml)
    
    # Access the data
    print(f"File: {taxonomy.metadata.path}")
    print(f"Purpose: {taxonomy.metadata.purpose}")
    print(f"Total concepts: {len(taxonomy.concepts)}")
    print(f"\nFirst concept:")
    print(f"  ID: {taxonomy.concepts[0].id}")
    print(f"  Name: {taxonomy.concepts[0].name}")
    print(f"  Category: {taxonomy.concepts[0].category}")
    print(f"  Tags: {', '.join(taxonomy.concepts[0].tags)}")
    print(f"  Complexity: {taxonomy.concepts[0].complexity}")
    
    # Generate summary report
    print("\n" + generate_summary_report([taxonomy]))
